#! /bin/sh
# /etc/init.d/mystart

### BEGIN INIT INFO
# Provides: mystart
# Required-Start: $remote_fs $syslog $all 
# Required-Stop: $remote_fs $syslog 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start MY Application stuff
# Description:  Start my application specific stuff AFTER everything else has started
### END INIT INFO

USER=pi
HOME=/home/pi

export USER HOME

case "$1" in
 start)
  echo "Starting MYSTART.."
  #Insert your favoured settings for a VNC session
  su - $USER -c "pulseaudio -D"
  ;;

 stop)
  echo "Stopping MYSTART..."
  ;;

 *)
  echo "Usage: /etc/init.d/mystart {start|stop}"
  exit 1
  ;;
esac

exit 0
